### ISSUE TITLE
Small note to avoid some Boost errors on Windows

### ISSUE THREAD

**Issue by moebiussurfing** [funatsufumiya/ofxAsync#1]
Hello, thanks for the add-on.
I just wanted to mention that I was having weird errors if the line `#include "ofxAsync.h"` was not at the starting of the ofApp.h file.

## ofApp.h
```.cpp
#include "ofMain.h"
#include "ofxAsync.h"

#include "ofxWord2Vec.h"
#include "ofxSurfingTextSubtitle.h"
#include "ofxSurfingImGui.h"
..
```

**Comment by ffunatsu** [comment]
@moebiussurfing Thank you for the feedback. Could you tell me more detail about the error? (error logs, compiler version, OF version or so)

**Comment by moebiussurfing** [comment]
Sure, 
it's a weird behavior.
just moving down the line like that:
```
#include "ofMain.h"

#include "ofxWord2Vec.h"
#include "ofxSurfingTextSubtitle.h"
#include "ofxSurfingImGui.h"
#include "ofxAsync.h" // <-
```

I am getting these errors:
```.bash
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2761	'boost::none_t::init_tag ': redeclaration of member is not allowed (compiling source file src\main.cpp)	W2V-subs	C:\Users\moebi\OneDrive\Documents\openFrameworks\libs\boost\include\boost\none.hpp	52	
Error	C2761	'boost::none_t::init_tag ': redeclaration of member is not allowed (compiling source file src\ofApp.cpp)	W2V-subs	C:\Users\moebi\OneDrive\Documents\openFrameworks\libs\boost\include\boost\none.hpp	52	
Error	C2661	'boost::none_t::none_t': no overloaded function takes 3 arguments (compiling source file src\main.cpp)	W2V-subs	C:\Users\moebi\OneDrive\Documents\openFrameworks\libs\boost\include\boost\none.hpp	52	
Error	C2661	'boost::none_t::none_t': no overloaded function takes 3 arguments (compiling source file src\ofApp.cpp)	W2V-subs	C:\Users\moebi\OneDrive\Documents\openFrameworks\libs\boost\include\boost\none.hpp	52	
Error	C2143	syntax error: missing ';' before '(' (compiling source file src\main.cpp)	W2V-subs	C:\Users\moebi\OneDrive\Documents\openFrameworks\libs\boost\include\boost\none.hpp	52	
Error	C2143	syntax error: missing ';' before '(' (compiling source file src\ofApp.cpp)	W2V-subs	C:\Users\moebi\OneDrive\Documents\openFrameworks\libs\boost\include\boost\none.hpp	52	
```

I am using Visual Studio 2022. oF GitHub patch-release branch,

![image](https://user-images.githubusercontent.com/2106149/199645302-7b8f4414-6bd3-46f7-a45e-0f737dcf8864.png)

**Comment by moebiussurfing** [comment]
Hey @funatsufumiya ,

Did you still using this add-on?
Do you use it on Windows or other platform?

I am having the error when adding the header into an add-on, and putting at the end of the included headers...
#include "ofxAsync.h" 

But I am having these errors again. 
My workaround was to move the line down, but can't do it here.

Best

**Comment by ffunatsu** [comment]
@moebiussurfing 
Sorry for very late reaction to this thread.
I'm still using this addon on Windows, but cannot reproduce this error on oF 0.12.0.

**Comment by ffunatsu** [comment]
As workaround, I removed boost::optional and put trade-off notes.
